### ISSUE TITLE
Getting reference to the value

### ISSUE THREAD

**Issue by MaksimZh** [s-ludwig/taggedalgebraic#15]
```D
struct Foo {}
void boo(ref Foo f) {}

union FooU { Foo foo; }
alias Tagged = TaggedAlgebraic!FooU;

Tagged f = Foo();
```
There is no way to pass `f` to `boo` because the result of `cast(Foo) f` is r-value.

**Comment by schveiguy** [comment]
It's not just getting a reference to a value, even functions that return references don't work. I need member functions that return ref to be preserved as well.

```D
struct Foo {
   ref Foo getThis() { return this; }
}

union FooU { Foo foo; }
alias Tagged = TaggedAlgebraic!FooU;

Tagged f = Foo();
boo(f.getThis()); // fails
```

**Comment by s-ludwig** [comment]
There is [`get!T`](https://github.com/s-ludwig/taggedalgebraic/blob/4938007701c1e19ee374bb8c9dab8d79845c0e2b/source/taggedalgebraic/taggedalgebraic.d#L675) that can be used to get a reference.

I haven't tried `auto ref`, but that looks like it should work, apart from ambiguous return type cases.

**Comment by schveiguy** [comment]
Awesome! I can't remember now where I was going to used `TaggedAlgebraic` and used something else. I guess I will come across it again at some point lol.
