### ISSUE TITLE
Can't use self-referential array

### ISSUE THREAD

**Issue by unleashy** [s-ludwig/taggedalgebraic#19]
Hi! I have this code:

```d
import std.stdio;

import taggedalgebraic;

struct Foo
{
    union U
    {
        Foo[] array;
    }

    TaggedAlgebraic!U payload;
    alias payload this;

    this(T)(T value)
    {
        payload = value;
    }
}

void main()
{
    auto f1 = Foo(cast(Foo[]) []);
    auto f2 = Foo(cast(Foo[]) []);
    
    writeln(f1 == f2);
}
```

and when compiling it, I get this error:

```d
Error: template taggedalgebraic.TaggedAlgebraic!(U).TaggedAlgebraic.opEquals cannot deduce function from argument types !()(Foo), candidates are:
    taggedalgebraic.TaggedAlgebraic!(U).TaggedAlgebraic.opEquals(T, this TA)(auto ref T other) if (is(Unqual!T == TaggedAlgebraic) || hasOp!(TA, OpKind.binary, "==", T))
Error: template instance `object.__equals!(Foo, Foo)` error instantiating
source\app.d(26,13):        instantiated from here: opEquals!(TaggedAlgebraic!(U), TaggedAlgebraic!(U))
```

however, if I replace `Foo` in `Foo[] array` with anything other than the self-referential type, like say, `int` (to become `int[] array`, and also replacing the cast in main) it compiles and runs as expected, printing "true" to the console.

Is this the expected behaviour? Is there any reason for self-referential arrays to not work like I non-self-referential ones? I'm using `dmd v2.082.0`.

Thank you!

**Comment by s-ludwig** [comment]
The problem here is that the compiler expands `f1 == f2` to `f1.payload.opEquals(f2)` instead of `f1.payload.opEquals(f2.payload)` and no comparison between `TaggedAlgebraic!U` and `Foo` is defined, only between two `TaggedAlgebraic!U` values.

To solve the issue, `Foo` needs to explicitly define its own `opEquals` (possibly also a `const` or `ref` overload):
```
    bool opEquals(Foo other) { return this.payload == other.payload; }
```

Disclaimer: I didn't actually try to compile the proposed fix, so this needs to be taken with a grain of salt.

**Comment by unleashy** [comment]
Ah yeah, this fixed it. Thanks!

**Comment by s-ludwig** [comment]
BTW, the latest version now als allows to define self-referential types in a nicer way using the `This` type, which should also fix this issue:

```
union U
{
    TaggedAlgebraic!This[] array;
}

alias Foo = TaggedAlgebraic!U;
```

See also #24.

**Comment by unleashy** [comment]
Oh, good! Thank you again!
