### ISSUE TITLE
needs some tests

### ISSUE THREAD

**Issue by MartinNowak** [s-ludwig/taggedalgebraic#2]

**Comment by MartinNowak** [comment]
The existing tests fail btw.
```d
core.exception.AssertError@source/taggedalgebraic.d(138): Cannot cast a integer value to short
```

**Comment by s-ludwig** [comment]
I've looked over the test coverage and it seems to be fully covered. The lines that are shown as uncovered are mostly code executed during CTFE, or `assert(false)` statements. Not sure what to do about those to make the percentage more appealing...
