### ISSUE TITLE
Add visit/tryVisit similar to what Variant offers.

### ISSUE THREAD

**Issue by s-ludwig** [s-ludwig/taggedalgebraic#3]
See https://github.com/s-ludwig/std_data_json/issues/17

**Comment by s-ludwig** [comment]
Just noticed that `visit` is actually a superset of `apply`, so this is indeed a natural direction to take.

**Comment by schveiguy** [comment]
Should this be closed? I think it was added.

**Comment by schveiguy** [comment]
OK, now I see it was only added for TaggedUnion. But a TaggedAglebraic version would be trivial... Will make a PR.

**Comment by s-ludwig** [comment]
With #20 and #42 this is now implemented for both, `TaggedUnion` and `TaggedAlgebraic`.
