### ISSUE TITLE
Make 'TaggedAlgebraic.Union' public instead of private

### ISSUE THREAD

**Issue by drug007** [s-ludwig/taggedalgebraic#6]
It allows to do more with TA. For example I'd like to generate code for TA, but now I should store somewhere a struct/union I've passed to TA to be able to do so. It's not only annoying, it makes explicitly import this struct/union and so makes my code less generic.
Is there the reason to have 'Union' private?

**Comment by s-ludwig** [comment]
I guess the only argument for having it private would be to keep the namespace pollution to a minimum. But I guess that actually private doesn't really make a difference anyway, because it just controls access and not visibility. I'll make it public.

**Comment by s-ludwig** [comment]
Fixed by 4a506f458bc9b5795de38b18b436b7a9ff52c91a.

**Comment by drug007** [comment]
Thanks!
