### ISSUE TITLE
Using with gc

### ISSUE THREAD

**Issue by drug007** [s-ludwig/taggedalgebraic#7]
I use taggedalgebraic with struct that has indirection managed by gc and gc collects my data during run-time. what is the best way to avoid it? I've tried to use GC.addRange in ctors, but it seems not enough.

**Comment by s-ludwig** [comment]
TaggedAlgebraic itself should be properly scanned by the GC under normal circumstances, as it uses `void[]` to store the payload. Is it possible that the TaggedAlgebraic itself is allocated in a memory area that is not registered with the GC?

**Comment by drug007** [comment]
I see. Unfortunately, TaggedAlgebraic is allocated in gc managed memory, so it's something else. I close this issue until I'll have more details about it.
